import type { Metadata, Viewport } from "next";
import MyAppBar from "@/components/appBar";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import { Container, Grid2, Typography } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyAppBar />
        <Container maxWidth="xl" sx={{ mt: 2 }}>
          <Grid2 container spacing={2}>
            <Grid2 size={8}>
              <Typography variant="h5">Articles</Typography>
              {children}
            </Grid2>
            <Grid2 size={4}>{children}</Grid2>
          </Grid2>
        </Container>
      </body>
    </html>
  );
}
